import { describe, it, expect } from "vitest";
import { Repository } from "../repository";
import { MetadataStorage, defineModel } from "../model";
import { DataTypes, DBType, RelationType } from "../types";

/**
 * A model class as it appears when it was created by a *different copy* of the
 * ORM: the metadata lives on the class statics, while the MetadataStorage
 * registry of this module knows nothing about it.
 *
 * This is what a duplicate dependency or a mixed CJS/ESM build produces, and it
 * used to silently disable validation, optimistic locking and relation loading.
 */
class Post {
  static tableName = "posts";
  constructor(public data?: any) {}
}

class User {
  static tableName = "users";
  static versioned = true;
  static softDelete = false;
  static columns: any = {
    id: { type: DataTypes.INTEGER, required: true },
    title: { type: DataTypes.STRING, required: true },
    username: { type: DataTypes.STRING, minLength: 3, maxLength: 10 },
    email: {
      type: DataTypes.STRING,
      pattern: /@example\.com$/,
    },
    handle: {
      type: DataTypes.STRING,
      customValidator: (val: string) =>
        val.startsWith("@") || "Handle must start with @",
    },
    deleted_at: { type: DataTypes.DATETIME, softDelete: true },
    version: { type: DataTypes.INTEGER, optimisticLock: true },
  };
  static relations: any = [
    {
      type: RelationType.ManyToOne,
      target: () => Post,
      property: "posts",
      foreignKey: "user_id",
    },
  ];
  static timestamps = { createdAt: "created_at", updatedAt: "updated_at" };
  constructor(public data?: any) {}
}

const fakeClient: any = { config: { type: DBType.SQLite } };

describe("metadata resolution across bundle boundaries", () => {
  it("should read table name, versioning and timestamps from class statics", () => {
    const repo: any = new Repository(fakeClient, User);

    expect(repo.table).toBe("users");
    expect(repo.versioned).toBe(true);
    expect(repo.timestampsConfig).toEqual({
      createdAt: "created_at",
      updatedAt: "updated_at",
    });
  });

  it("should detect the soft delete and optimistic lock columns", () => {
    const repo: any = new Repository(fakeClient, User);

    expect(repo.softDeleteField).toBe("deleted_at");
    expect(repo.optimisticLockField).toBe("version");
  });

  it("should key relations by property name rather than array index", () => {
    const repo: any = new Repository(fakeClient, User);

    expect(Object.keys(repo.relations)).toEqual(["posts"]);
    expect(repo.relations.posts.targetModel()).toBe(Post);
    expect(repo.relations.posts.foreignKey).toBe("user_id");
  });

  it("should enforce length, pattern and custom validators", () => {
    const repo: any = new Repository(fakeClient, User);

    const base = { title: "Hello" };

    expect(() => repo.validate({ ...base, username: "ab" })).toThrow("too short");
    expect(() => repo.validate({ ...base, username: "abcdefghijk" })).toThrow(
      "too long",
    );
    expect(() => repo.validate({ ...base, email: "x@nope.com" })).toThrow(
      "does not match pattern",
    );
    expect(() => repo.validate({ ...base, handle: "someone" })).toThrow(
      "Handle must start with @",
    );
    expect(() =>
      repo.validate({
        ...base,
        email: "someone@example.com",
        handle: "@someone",
      }),
    ).not.toThrow();
  });

  it("should enforce required columns", () => {
    const repo: any = new Repository(fakeClient, User);

    expect(() => repo.validate({})).toThrow("required");
    expect(() => repo.validate({ title: "Hello" })).not.toThrow();
  });

  it("should exempt an auto-increment primary key from `required`", () => {
    const repo: any = new Repository(fakeClient, User);

    // `id: { type: DataTypes.INTEGER, required: true }` is the documented
    // spelling of an auto-increment PK, so the database supplies the value.
    expect(repo.autoIncrementField).toBe("id");
    expect(() => repo.validate({ title: "Hello" })).not.toThrow();

    // A string/UUID primary key is generated by the caller, so it stays required.
    const Uuid = defineModel({
      tableName: "uuid_models",
      columns: {
        id: { type: DataTypes.UUID, required: true },
        title: { type: DataTypes.STRING, required: true },
      },
    });
    const uuidRepo: any = new Repository(fakeClient, Uuid);
    expect(uuidRepo.autoIncrementField).toBeNull();
    expect(() => uuidRepo.validate({ title: "Hello" })).toThrow("required");
  });
});

describe("MetadataStorage cross-copy sharing", () => {
  it("should anchor the registry on globalThis so copies share one map", () => {
    const registry = (globalThis as any)[
      Symbol.for("stabilize-orm.model-registry")
    ];

    expect(registry).toBeInstanceOf(Map);
    // A model defined here must be visible to every copy reading that map.
    const Article = defineModel({
      tableName: "articles",
      columns: { id: { type: DataTypes.INTEGER, required: true } },
    });
    expect(registry.get(Article)).toBeDefined();
    expect(MetadataStorage.getModelByTableName("articles")).toBe(Article);
  });

  it("should resolve validators from class statics", () => {
    expect(MetadataStorage.getValidators(User)).toEqual({
      id: ["required"],
      title: ["required"],
      username: [],
      email: [],
      handle: [],
      deleted_at: [],
      version: [],
    });
  });

  it("should prefer the registry entry over class statics", () => {
    const Local = defineModel({
      tableName: "local_only",
      columns: { id: { type: DataTypes.INTEGER, required: true } },
    });

    expect(MetadataStorage.getTableName(Local)).toBe("local_only");
    expect(MetadataStorage.getModelMetadata(Local)?.tableName).toBe(
      "local_only",
    );
  });
});
