name: Stabilize ORM CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Install dependencies (bun install)
        run: bun install